# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0704d3718ed185885390a7143fa9cab958d09535f66537a303441987a22fb635379101f5bc33581bb903af08cc785201c723a2b351c9bbdbfb17f46593c7001b

test:
  secret_key_base: e3c542513ea43a3600ce40bf80209ba9273139d2ca87580c891ab702ba58ac8dbfae13446c3593541e496e1ba1ceb7223dbbb64d09854a6c0d98f3c821275478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
