# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1962415eeb0819f00972fc53f8fd362406db06ebf54e39f9d2a69b2e823b2388de8affa586fd1d610c37f0ef72f518af7b1c3340da09112914d0e49f63b84b

test:
  secret_key_base: 24f577261d9ef3b2c643ff0663b2c1e4b79b9f8442192c470bc265593455c8cf9714e40d3ab6bed93b730d5c5d2651f29da4c617c79b7a12313071f805604ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
