# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0684297b86fad02fc9a43eb8b94507be8576bf654b9548cae11a1bd7822ff64298d1f758af7e22d2a7a6d81d919ea2800bc9c0f2a243bb2adfec94f7a9ab2497

test:
  secret_key_base: b3f3882e5816107334bce59e1c1250e3cc28982487b31f78d87cf2730054f6c509062d1f9459368f129d936470c62f075e9d286175a72ef7b6dafbce0d139549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
