# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01cd650d4b90ab7039d0fe5c307119c12df0567994e7d468faa934d3bf25ab22b08ffff6c4fca89595f46e880864ad62214251567f962c73c5881128c39f977

test:
  secret_key_base: d53713ca64f28db0329db10bf5a1e6060cb7bdee9a85c600db1aa86d9e3fb4730d85f29267f1b124e4f73727a30aa7a00012cca13d86787df45137abb62544c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
