# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d10af20d6af7fb0a1743fbef734bb1b77e4f93b2800096f5b76eb4fb9998e16173309ce656abaabe43be9efe7554cc7e1ae3fd577f8fa57861908c6ee07e7ef1

test:
  secret_key_base: 0f6b9984b599f75a8d9676b7f34b605be22daf92879b1df5a1c1f0e82eae0fb9502c4faae6f6d168ec363c9bcb8504191cff88da7d48e85425ddfe15e46a294c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
