# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb267f9fa16ad38828dbc67ac02a921b9a108f710c12c9a77efbe12aadaf3a7ce520dba4fb4fb101263c36a1a87bc06f8fe2882670370aa75c1b7d7cfa632609

test:
  secret_key_base: fa0468f3090e0c8e4e2c1049d1b67b1c1196a28b59154842dde4dcd1c18581935dc1ac9f57f5d141c41b67ef2a42ea097bc2ab6c0693cdf3a979c8a33daf28ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
